### PR TITLE
WIP: Tracer per instrumentation library, flow through to SpanInfo

### PR DESCRIPTION
**Pull request by HaloFour**
Explore handling `TracerProvider` and instrumentation library info "correctly".  It involves being able to provide a different tracer per library name+version and each span created by that tracer will have that library info written into it.  That will then be copied into the SpanInfo.

### CODE REVIEW

**Comment by HaloFour** [comment]
It might be possible to simplify by exposing the instrumentation library on the span interface and making it mutable, then I might be able to use a decorator to update the library info on the span after the span is created vs. creating new tracers.  But this is as far as I've gotten tonight.

**Comment by ptravers** [comment]
@HaloFour  do you still need me to look at this? after the last PR

**Comment by HaloFour** [comment]
Obsolete

**Comment by HaloFour** [comment]
Nope, the other PR took care of the same concerns in a cleaner way.

**Pull request closed without merging**
